name: Check release
on:
  workflow_call:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Check release correctness
        run: |
          pwd
          cd products
          pwd
          project_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          if [ $project_version != $RELEASE_VERSION ]; then
            echo "Project version and Release version are not equal, please create tag using workflow specified for this"
            exit 1
          fi

          git fetch origin
          commit_id=$(git rev-parse HEAD)
          echo "commit id we are going to check $commit_id"
          contain_commit=$(git branch -r --contains $commit_id)
          echo "remote branches which contain $commit_id: $contain_commit"
          if [[ ! ${contain_commit} =~ "origin/main" ]]; then
            echo "Main branch does not contain release commit"
            exit 1
          fi

        env:
          RELEASE_VERSION: ${{ github.event.release.tag_name }}

      - name: Build with Maven
        run: |
          cd products
          mvn -B package --file pom.xml -Dmaven.test.skip
