name: CI
on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Allows to run this workflow from another workflow
  workflow_call:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: IgniteMigrationToolTests
        run: docker-compose --compatibility -f ./products/docker-compose.yml up
          --force-recreate --abort-on-container-exit --exit-code-from tests_ignitemigrationtool --no-color tests_ignitemigrationtool

      - name: PatchToolsTests
        run: docker-compose --compatibility -f ./products/docker-compose.yml up
          --force-recreate --abort-on-container-exit --exit-code-from tests_patchtools --no-color tests_patchtools

      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
        with:
          check_name: show-test-results
          report_paths: '**/surefire-reports/TEST-TestSuite.xml'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./products/core/tests-ignitemigrationtool/site/jacoco/jacoco.xml,
            ./products/patchtools/tests-patchtools/site/jacoco/jacoco.xml
