name: Publish modules to the Maven Central Repository and GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Update project version in pom files
        run: |
          git config --global user.name $GITHUB_USERNAME
          git config --global user.email $GITHUB_USERNAME@users.noreply.github.com

          mvn -B versions:set -DnewVersion=${RELEASE_VERSION} -DgenerateBackupPoms=false

        env:
          GITHUB_USERNAME: ${{ github.actor }}
          RELEASE_VERSION: ${{ github.event.release.tag_name }}

      - name: Create a release PR into repository
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Release ${{ github.event.release.tag_name }}
          base: main
          branch: release-${{ github.event.release.tag_name }}-change

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to the Maven Central Repository
        run: mvn -Ppublish,central --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages
        run: mvn -Ppublish,github --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
