name: Publish modules to the Maven Central Repository and GitHub Packages
on:
  # Allows to run this workflow from another workflow
  workflow_call:
    secrets:
      OSSRH_USERNAME:
        required: true
      OSSRH_TOKEN:
        required: true
      MAVEN_GPG_PRIVATE_KEY:
        required: true
      MAVEN_GPG_PASSPHRASE:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import

      - name: Publish to the Maven Central Repository
        run: |
          cd products
          mvn -Ppublish,central --batch-mode -Dmaven.test.skip deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Publish to GitHub Packages
        run: |
          cd products
          mvn -Ppublish,github --batch-mode -Dmaven.test.skip deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
