name: Release Cycle
on:
  release:
    types: [created]
jobs:
  mainCI:
    uses: ./.github/workflows/main.yml
  demoCI:
    needs: [ mainCI ]
    uses: ./.github/workflows/demo.yml
  checkRelease:
    needs: [ mainCI, demoCI ]
    uses: ./.github/workflows/check_release.yml
  release:
    needs: [ mainCI, demoCI, checkRelease ]
    uses: ./.github/workflows/publish.yml
    secrets:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
  updateReleaseSuccess:
    needs: [ release ]
    uses: ./.github/workflows/update_release.yml
    with:
      text: "Release Cycle finished with success"
  updateReleaseFailed:
    needs: [ release ]
    if: always() && needs.release.result != 'success'
    uses: ./.github/workflows/update_release.yml
    with:
      text: "!!ATTENTION!! Release Cycle failed, please see actions results"

