name: Update release body with results
on:
  workflow_call:
    inputs:
      text:
        required: true
        type: string
jobs:
  updateReleaseBody:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update release with results
        uses: tubone24/update_release@v1.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          is_append_body: true
          body: ${{ inputs.text }}, [build url](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
